version: '3'

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - passmanager
    shm_size: 1g

 
networks:
  passmanager:
    external: true

volumes:
  postgres:
